FROM python:3.10-slim

WORKDIR /app
COPY . /app

RUN pip install --upgrade pip setuptools wheel && \
    pip install -r "4. Projetos/7. Projeto Modulo Streamlit e Pycaret/requirements.txt"

EXPOSE 8501
CMD ["streamlit", "run", "4. Projetos/7. Projeto Modulo Streamlit e Pycaret/Streamlit/projeto.py", "--server.port=8501", "--server.address=0.0.0.0"]
